// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react'

import { PlasmicExclusiveIntroductoryCard } from './plasmic/cadmenclinic_migration/PlasmicExclusiveIntroductoryCard'
import { ctaToBooking } from '@/helpers/cta_to_booking'
import { ctaToBookingServiceCategory } from '@/helpers/cta_to_booking_service_category'

function ExclusiveIntroductoryCard_(props, ref) {
  const handleNav = (category, service) => {
    if (category) {
      ctaToBookingServiceCategory(category)
    } else if (service) {
      ctaToBooking(service)
    }
  }

  return (
    <PlasmicExclusiveIntroductoryCard
      root={{ ref }}
      {...props}
      exclusiveIntroductoryButton={{
        onClick: (e) => {
          handleNav(props.category, props.service)
        }
      }}
    />
  )
}

const ExclusiveIntroductoryCard = React.forwardRef(ExclusiveIntroductoryCard_)

export default ExclusiveIntroductoryCard
