/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fpxTiFS69ULcX4wDGEfw3c
// Component: 9rME71zJbGo1
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateStateOnChangeProp,
  generateStateValueProp,
  hasVariant,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import TopNav from "../../TopNav"; // plasmic-import: xBvtLE-eO4gb/component
import DiscountPricingPill from "../../DiscountPricingPill"; // plasmic-import: TO66K8qjr8TP/component
import Button from "../../Button"; // plasmic-import: 0o-OkGmTYJg3/component
import TextNavLink from "../../TextNavLink"; // plasmic-import: EItg-PDL8JJi/component
import IconLayeredCircles from "../../IconLayeredCircles"; // plasmic-import: otc6Jw_feodx/component
import HowItWorksCard from "../../HowItWorksCard"; // plasmic-import: w7EJDoU6NMVc/component
import AreasInteractive from "../../AreasInteractive"; // plasmic-import: cNLJfmXsSSOr/component
import TestimonialsSlider from "@/components/TestimonialsSlider/TestimonialsSlider"; // plasmic-import: J0SSSRogRoTR/codeComponent
import TestimonialCard from "../../TestimonialCard"; // plasmic-import: zWVJ2Qd7n2nR/component
import AreaExplainerCard from "../../AreaExplainerCard"; // plasmic-import: 4NENsursTaMC/component
import BigTestimonial from "../../BigTestimonial"; // plasmic-import: qZkEECWSrv1-/component
import Faq from "../../Faq"; // plasmic-import: kXqZTEGKWOeX/component
import { Video } from "@plasmicpkgs/plasmic-basic-components";
import OurLocationSection from "../../OurLocationSection"; // plasmic-import: 90jT_0Y9mL-p/component
import FooterNew from "../../FooterNew"; // plasmic-import: NE5t6IteXed-/component
import { useScreenVariants as useScreenVariants_4IUcgkiijTv2 } from "../blank_website/PlasmicGlobalVariant__Screen"; // plasmic-import: 4iUCGKIIJTv2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../blank_website/plasmic.module.css"; // plasmic-import: fpxTiFS69ULcX4wDGEfw3c/projectcss
import sty from "./CadmenPRPLander.module.css"; // plasmic-import: 9rME71zJbGo1/css
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: fgEQ3xZTbtTI/icon
import VectorHeartSvgIcon from "./icons/PlasmicIcon__VectorHeartSvg"; // plasmic-import: JbM7XFcjDUEn/icon
import VectorPersonSvgIcon from "./icons/PlasmicIcon__VectorPersonSvg"; // plasmic-import: OvyHUiQ4SEzz/icon
import Image from "next/image";

// newly created components
import RatingReviewPill from "@/components/RatingReviewPill";
import AffordableHairRestoration from "@/components/AffordableHairRestoration";
import ServiceStepCard from "@/components/ServiceStepCard";
import WhyPeopleChooseCard from "@/components/WhyPeopleChooseCard";
import SmallInfoCard from "@/components/SmallInfoCard";

createPlasmicElementProxy;

export const PlasmicBotoxLander__VariantProps = new Array();

export const PlasmicBotoxLander__ArgProps = ["serviceData"];

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBotoxLander__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  // Define service data
  const service = args.serviceData ?? {};

  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_4IUcgkiijTv2()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">CadmenClinic | {service.general.shortTitle}</title>
        <meta
          key="og:title"
          property="og:title"
          content={service.general.longTitle}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={service.general.longTitle}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          {/* HERO SECTION */}
          <section
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__vUeE3)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___024F)}>
                <DiscountPricingPill
                  className={classNames(
                    "__wab_instance",
                    sty.discountPricingPill__lyb
                  )}
                  perUnit={"/session"}
                  salePrice={service.general.salePrice}
                  strikePrice={service.general.strikePrice}
                />

                <div className={classNames(projectcss.all, sty.freeBox__xeJeY)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___6RoWb)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1___1NJ,
                        ".h1-plasmic"
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{service.hero.tagline}{" with \n"}</React.Fragment>
                        <span
                          style={{
                            fontWeight: 500,
                            fontStyle: "italic",
                            color: "#D19D51",
                            fontSize: "90%"
                          }}
                        >
                          {service.general.longTitle}
                        </span>
                      </React.Fragment>
                    </h1>
                  </div>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__kl4Li
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Claim your exclusive "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700, color: "#000000" }}
                      >
                        {"50% offer"}
                      </span>
                      <React.Fragment>
                        {" now & naturally promote new hair growth using "}
                        {service.hero.description}
                      </React.Fragment>
                    </React.Fragment>
                  </p>
                </div>
                <div style={{marginBottom: "25px"}}>
                  <RatingReviewPill />
                </div>
                
                <Link href='https://cadmenclinic.ca.zenoti.com/webstoreNew/services' target="_blank" className='mt-[10px] w-full md:w-auto'>
                  <button className='button w-full md:w-auto'>Book Now</button>
                </Link>
              
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__wyX9A)}>
                <PlasmicImg__
                  data-plasmic-name={"heroImage"}
                  data-plasmic-override={overrides.heroImage}
                  alt={""}
                  className={classNames(sty.heroImage)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"120%"}
                  displayMinWidth={"100%"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: service.hero.img,
                    fullWidth: 1605,
                    fullHeight: 1351,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </section>

          {/* THREE CARDS SECTION */}
          <section
            data-plasmic-name={"threeCardsSection"}
            data-plasmic-override={overrides.threeCardsSection}
            className={classNames(projectcss.all, sty.threeCardsSection)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"threeCards"}
              data-plasmic-override={overrides.threeCards}
              hasGap={true}
              className={classNames(projectcss.all, sty.threeCards)}
            >
              <SmallInfoCard
                icon="/icons/portrait-icon.svg"
                emphasis="FREE"
                title=" Consultation"
                subtitle="Claim your first consultation for <strong>FREE</strong>"
              />
              <SmallInfoCard
                icon="/icons/discount.svg"
                emphasis={service.general.salePrice}
                title=" Special Price!"
                subtitle="Exclusive <strong>50% discount</strong> for your first procedure"
              />
              <SmallInfoCard
                icon="/icons/star.svg"
                emphasis="Trusted"
                title=" by 2,100+ Patients"
                subtitle="Proven results, 100% natural, minimal downtime"
              />
            </Stack__>
          </section>

          {/* CHOOSE SERVICE SECTION */}
          <section className={classNames(projectcss.all, sty.chooseBotoxSection)}>
            <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__jhpM3
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        fontStyle: "italic",
                        fontWeight: 500,
                        color: "#D19D51"
                      }}
                    >
                      {"Why People Choose "}
                    </span>
                    <React.Fragment>{service.general.longTitle}</React.Fragment>
                  </React.Fragment>
                </h2>
                <p
                className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.__wab_text,
                    sty.p__zSnqu
                  )}
                  style={{
                    maxWidth: "800px",
                    paddingTop: "20px"
                  }}
                >
                  {service.whyPeopleChoose.description}
                </p>
              
            <div className="cards-container">
              {/* What is service */}
              <WhyPeopleChooseCard
                icon="/icons/syringe-icon.svg"
                title={`What is <strong><em>${service.general.longTitle}</em></strong>?`}
                img={service.whyPeopleChoose.what.img}
                description={service.whyPeopleChoose.what.description}
              />

              {/* why people choose service */}
              <WhyPeopleChooseCard
                icon="/icons/portrait-icon.svg"
                title={`Why <strong><em>People Choose</em></strong> ${service.general.shortTitle}?`}
                img={service.whyPeopleChoose.why.img}
                description={service.whyPeopleChoose.why.description}
              />

              {/* Safe and Professional care */}
              <WhyPeopleChooseCard
                icon="/icons/heart-icon.svg"
                title="<strong><em>Safe & Professional</em></strong> Care"
                img="/media/services/prp/section3/3.jpeg"
                description="Your safety is our top priority. Our licensed professionals use industry-leading techniques in a controlled, sterile environment. We believe in natural-looking results that allow your natural beauty to shine."
              />
            </div>

            <Link href='https://cadmenclinic.ca.zenoti.com/webstoreNew/services' className='mt-[40px] w-full md:w-auto'>
              <button className='button w-full md:w-auto'>Book Now</button>
            </Link>

            <style jsx>{`
              .cards-container {
                display: flex; /* Makes items arrange in a row */
                flex-wrap: wrap; /* Allows items to wrap to the next line if space runs out */
                justify-content: center; /* Centers the cards horizontally */
                gap: 20px; /* Adds space between cards (optional, but good for visual separation) */
                padding: 20px; /* Adds some padding around the container */
                box-sizing: border-box; /* Ensures padding doesn't add to total width unexpectedly */
                max-width: 100%; /* Ensures the container takes full available width *
              }
            `}</style>
          </section>

          {/* HOW SERVICE WORKS */}
          <section
            data-plasmic-name={"howBotoxWorksSection"}
            data-plasmic-override={overrides.howBotoxWorksSection}
            className={classNames(projectcss.all, sty.howBotoxWorksSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__jomPy)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"howBotoxWorksHeader"}
                data-plasmic-override={overrides.howBotoxWorksHeader}
                hasGap={true}
                className={classNames(projectcss.all, sty.howBotoxWorksHeader)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__egivG
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        fontStyle: "italic",
                        fontWeight: 500,
                        color: "#FAD8A7"
                      }}
                    >
                      {"How"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FAD8A7" }}
                    >
                      {" "}
                    </span>
                    <React.Fragment>
                      {service.general.longTitle}
                      {" Works"}
                    </React.Fragment>
                  </React.Fragment>
                </h2>
                <p
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.__wab_text,
                    sty.p__l5CD
                  )}
                >
                  {
                    "Our patients have experienced significant hair regrowth with our science-backed approach, ensuring safe, long-lasting, and incredible results"
                  }
                </p>
              </Stack__>
              <div className="cards-container">
                {/* img, id, title, description */}
                {service.howItWorks.map((step) => (
                  <ServiceStepCard 
                    key={step.id}
                    img={step.img}
                    id={step.id}
                    title={step.title}
                    description={step.description}
                  />
                ))}
              </div>

              {/* Add a style block for the container */}
              <style jsx>{`
                .cards-container {
                  display: flex;
                  flex-wrap: wrap;
                  justify-content: space-between;
                  gap: 20px;
                  padding: 20px;
                  box-sizing: border-box;
                  width: 100%;
                }

                @media (max-width: 1023px) {
                  .cards-container {
                    flex-direction: column;
                  }
                }
              `}</style>
            </Stack__>
          </section>

          {/* INTERACTIVE AREA */}
          <AffordableHairRestoration/>

          {/* BEFORE AFTER */}
          <section
            data-plasmic-name={"beforeAfterSection"}
            data-plasmic-override={overrides.beforeAfterSection}
            className={classNames(projectcss.all, sty.beforeAfterSection)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"beforeAfterHeader"}
              data-plasmic-override={overrides.beforeAfterHeader}
              hasGap={true}
              className={classNames(projectcss.all, sty.beforeAfterHeader)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__yHrxl
                )}
              >
                <React.Fragment>
                  <React.Fragment>{"Before & "}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      fontStyle: "italic",
                      fontWeight: 500,
                      color: "#FAD8A7"
                    }}
                  >
                    {"After"}
                  </span>
                </React.Fragment>
              </h2>
              <p
                className={classNames(
                  projectcss.all,
                  projectcss.p,
                  projectcss.__wab_text,
                  sty.p__en7Rd
                )}
              >
                {"Results speak for themselves."}
              </p>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__bOf5N)}>
              <TestimonialsSlider
                data-plasmic-name={"beforeAfterSlider"}
                data-plasmic-override={overrides.beforeAfterSlider}
                className={classNames("__wab_instance", sty.beforeAfterSlider)}
                ctaLink={"#"}
                ctaText={"Act Now"}
                isDarkBg={false}
                settings={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? {
                        dots: false,
                        arrows: false,
                        infinite: true,
                        speed: 500,
                        slidesToShow: 1,
                        slidesToScroll: 1
                      }
                    : hasVariant(globalVariants, "screen", "midsize")
                    ? {
                        dots: false,
                        arrows: false,
                        infinite: true,
                        speed: 500,
                        slidesToShow: 2,
                        slidesToScroll: 1
                      }
                    : {
                        dots: false,
                        arrows: false,
                        infinite: true,
                        speed: 500,
                        slidesToShow: 3,
                        slidesToScroll: 1
                      }
                }
              >
                {service.beforeAfters.map((beforeAfter) => (
                  <TestimonialCard
                    className={classNames(
                      "__wab_instance",
                      sty.testimonialCard__rFqgo
                    )}
                    id={beforeAfter.id}
                    subtitle={beforeAfter.subtitle}
                    title={beforeAfter.title}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2Nkey)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: beforeAfter.img,
                        fullWidth: 486,
                        fullHeight: 480,
                        aspectRatio: undefined
                      }}
                    />
                  </TestimonialCard>
                ))}
              </TestimonialsSlider>
            </div>
          </section>

          {/* SERVICE TRANSFORMED/HELPED */}
          <section
            data-plasmic-name={"botoxHelpedSection"}
            data-plasmic-override={overrides.botoxHelpedSection}
            className={classNames(projectcss.all, sty.botoxHelpedSection)}
          >
            
            {/* stack for all */}
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___9IgFv)}
            >

              {/* stack for left title */}
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__h0TYw)}
              >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__jJtq
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{service.transformations.title.first}</React.Fragment>
                      <span
                        // className={"plasmic_default__all plasmic_default__span"}
                        style={{
                          fontStyle: "italic",
                          fontWeight: 500,
                          color: "#D19D51"
                        }}
                      >
                        {service.transformations.title.emphasis}
                      </span>
                      <React.Fragment>{service.transformations.title.last}</React.Fragment>
                    </React.Fragment>
                  </h2>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p__aWpbi
                    )}
                  >
                    {"Don’t wait any longer to restore your hair – join the many satisfied clients who have already experienced the benefits of "}
                    {service.general.longTitle}
                  </p>
              </Stack__>

              <div className={classNames(projectcss.all, sty.freeBox___5Wi9P)}>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"botoxHelpedScroller"}
                  data-plasmic-override={overrides.botoxHelpedScroller}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    sty.botoxHelpedScroller,
                    hasVariant(globalVariants, "screen", "midsize")
                      ? "botox-helped-scroller"
                      : undefined
                  )}
                >
                  {service.transformations.cards.map((transformation) => (
                    <AreaExplainerCard
                      className={classNames(
                        "__wab_instance",
                        sty.areaExplainerCard__xBMjy
                      )}
                      id={transformation.id}
                      subtitle={transformation.subtitle}
                      title={transformation.title}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___1N6Yf)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: transformation.img,
                          fullWidth: 287,
                          fullHeight: 256,
                          aspectRatio: undefined
                        }}
                      />
                    </AreaExplainerCard>
                  ))}
                </Stack__>
              </div>
            </Stack__>
          </section>


          {/* TESTIMONIALS */}
          <section className={classNames(projectcss.all, sty.section__p5T3P)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__rD1Um)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__eeq1)}
              >
                <RatingReviewPill />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__otgId
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Join Our Satisfied \n"}</React.Fragment>
                    {/* <React.Fragment>{"PRP Hair Restoration"}</React.Fragment> */}
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        fontWeight: 500,
                        fontStyle: "italic",
                        color: "#d09d45"
                      }}
                    >
                      {service.general.longTitle}
                      {" Clients"}
                    </span>
                  </React.Fragment>
                </h2>
                <p
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.__wab_text,
                    sty.p__qhN8C
                  )}
                >
                  {"Over thousands of people have transformed their lives with "}
                  {service.general.longTitle}
                </p>
              </Stack__>
              <div className={classNames(projectcss.all, sty.freeBox__llpLu)}>
                <TestimonialsSlider
                  data-plasmic-name={"satisfiedClientsSlider"}
                  data-plasmic-override={overrides.satisfiedClientsSlider}
                  className={classNames(
                    "__wab_instance",
                    sty.satisfiedClientsSlider
                  )}
                  ctaLink={"#"}
                  ctaText={"Book Now"}
                  isDarkBg={true}
                  settings={{
                    dots: false,
                    arrows: false,
                    infinite: true,
                    speed: 500,
                    slidesToShow: 1,
                    slidesToScroll: 1
                  }}
                >
                  {service.testimonials.map((testimonial) => (
                    <BigTestimonial
                      key={testimonial.id}
                      quote={testimonial.quote}
                    />
                  ))}
                </TestimonialsSlider>
              </div>
            </Stack__>
          </section>

          {/* QUESTION ANSWERS FAQ */}
          <section className={classNames(projectcss.all, sty.section__qz9Z)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__d6O5E)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kmhJs)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__nCrwW
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Our "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        fontWeight: 500,
                        fontStyle: "italic",
                        color: "#D19D51"
                      }}
                    >
                      {"Answers"}
                    </span>
                    <React.Fragment>{"\nfor Your Questions"}</React.Fragment>
                  </React.Fragment>
                </h2>
                <p
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.__wab_text,
                    sty.p__sLxZu
                  )}
                >
                  {"Our clients have eliminated their doubts about "}
                  {service.general.longTitle}
                  {", and you can join them today!"}
                </p>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rlxr1)}
              >
                {service.faqs.map((faq) => (
                  <Faq
                    id={faq.id}
                    answer={faq.answer}
                    question={faq.question}
                  />
                ))}
              </Stack__>
            </Stack__>
          </section>


          {/* VIDEO */}
          <section className={classNames(projectcss.all, sty.section__kI06)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__zva01)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__alzRe
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <React.Fragment>{"Watch the\n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic", fontWeight: 500 }}
                    >
                      {service.general.longTitle}
                      {" Process"}
                    </span>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <React.Fragment>{"Watch the "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic", fontWeight: 500 }}
                    >
                      {service.general.longTitle}
                      {" Process"}
                    </span>
                  </React.Fragment>
                )}
              </h1>
              <div className={classNames(projectcss.all, sty.freeBox__vQFwz)}>
                <Video
                  data-plasmic-name={"htmlVideo"}
                  data-plasmic-override={overrides.htmlVideo}
                  className={classNames("__wab_instance", sty.htmlVideo)}
                  controls={true}
                  src={service.video.src}
                  muted={service.video.muted}
                />
              </div>
              <Link href='https://cadmenclinic.ca.zenoti.com/webstoreNew/services' target="_blank" className='mt-[10px] w-full md:w-auto'>
                <button className='button white w-full md:w-auto'>Try It Now</button>
              </Link>
            </Stack__>
          </section>


          {/* OUR LOCATION */}
          <OurLocationSection
            data-plasmic-name={"ourLocationSection"}
            data-plasmic-override={overrides.ourLocationSection}
            className={classNames("__wab_instance", sty.ourLocationSection)}
          />


          {/* CLAIM SPECIAL OFFER */}
          <section className={classNames(projectcss.all, sty.section__h2TW)}>
            <div className={classNames(projectcss.all, sty.freeBox__lSnUu)}>
              <DiscountPricingPill
                className={classNames(
                  "__wab_instance",
                  sty.discountPricingPill__dvwCm
                )}
                perUnit={" /session"}
                salePrice={service.general.salePrice}
                strikePrice={service.general.strikePrice}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yjqrs)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__lhEX
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Claim Your "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{
                        fontStyle: "italic",
                        fontWeight: 500,
                        color: "#FAD8A7"
                      }}
                    >
                      {"Special Offer"}
                    </span>
                    <React.Fragment>{" Now!"}</React.Fragment>
                  </React.Fragment>
                </h2>
                <p
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.__wab_text,
                    sty.p__meiVy
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {"Book your FREE consultation and get "}
                    </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"50% DISCOUNT"}
                    </span>
                    <React.Fragment>
                      {" for first "}
                      {service.general.longTitle}
                      {" procedure!"}
                    </React.Fragment>
                  </React.Fragment>
                </p>
              </Stack__>
              <Link href='https://cadmenclinic.ca.zenoti.com/webstoreNew/services' target="_blank" className='mt-[10px] w-full md:w-auto'>
                <button className='button white w-full md:w-auto'>Book Now</button>
              </Link>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "topNav",
    "hero",
    "heroButton",
    "heroImage",
    "threeCardsSection",
    "threeCards",
    "chooseBotoxSection",
    "chooseBotoxHeader",
    "peopleChooseNav",
    "chooseBotoxPoints",
    "chooseBotoxDot2",
    "chooseBotoxDot3",
    "chooseBotoxDot4",
    "chooseBotoxButton",
    "chooseBotoxImages",
    "button",
    "howBotoxWorksSection",
    "howBotoxWorksHeader",
    "howBotoxWorksCards",
    "howBotoxWorksCardsMobile",
    "areasInteractive",
    "beforeAfterSection",
    "beforeAfterHeader",
    "beforeAfterSlider",
    "botoxHelpedSection",
    "botoxHelpedScroller",
    "satisfiedClientsSlider",
    "htmlVideo",
    "videoCtaButton",
    "ourLocationSection",
    "specialOfferButton",
    "footerNew",
    "claimBotoxFooter"
  ],

  topNav: ["topNav"],
  hero: ["hero", "heroButton", "heroImage"],
  heroButton: ["heroButton"],
  heroImage: ["heroImage"],
  threeCardsSection: ["threeCardsSection", "threeCards"],
  threeCards: ["threeCards"],
  chooseBotoxSection: [
    "chooseBotoxSection",
    "chooseBotoxHeader",
    "peopleChooseNav",
    "chooseBotoxPoints",
    "chooseBotoxDot2",
    "chooseBotoxDot3",
    "chooseBotoxDot4",
    "chooseBotoxButton",
    "chooseBotoxImages",
    "button"
  ],

  chooseBotoxHeader: ["chooseBotoxHeader"],
  peopleChooseNav: ["peopleChooseNav"],
  chooseBotoxPoints: [
    "chooseBotoxPoints",
    "chooseBotoxDot2",
    "chooseBotoxDot3",
    "chooseBotoxDot4",
    "chooseBotoxButton"
  ],

  chooseBotoxDot2: ["chooseBotoxDot2"],
  chooseBotoxDot3: ["chooseBotoxDot3"],
  chooseBotoxDot4: ["chooseBotoxDot4"],
  chooseBotoxButton: ["chooseBotoxButton"],
  chooseBotoxImages: ["chooseBotoxImages"],
  button: ["button"],
  howBotoxWorksSection: [
    "howBotoxWorksSection",
    "howBotoxWorksHeader",
    "howBotoxWorksCards",
    "howBotoxWorksCardsMobile"
  ],

  howBotoxWorksHeader: ["howBotoxWorksHeader"],
  howBotoxWorksCards: ["howBotoxWorksCards"],
  howBotoxWorksCardsMobile: ["howBotoxWorksCardsMobile"],
  areasInteractive: ["areasInteractive"],
  beforeAfterSection: [
    "beforeAfterSection",
    "beforeAfterHeader",
    "beforeAfterSlider"
  ],

  beforeAfterHeader: ["beforeAfterHeader"],
  beforeAfterSlider: ["beforeAfterSlider"],
  botoxHelpedSection: ["botoxHelpedSection", "botoxHelpedScroller"],
  botoxHelpedScroller: ["botoxHelpedScroller"],
  satisfiedClientsSlider: ["satisfiedClientsSlider"],
  htmlVideo: ["htmlVideo"],
  videoCtaButton: ["videoCtaButton"],
  ourLocationSection: ["ourLocationSection"],
  specialOfferButton: ["specialOfferButton"],
  footerNew: ["footerNew", "claimBotoxFooter"],
  claimBotoxFooter: ["claimBotoxFooter"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBotoxLander__ArgProps,
          internalVariantPropNames: PlasmicBotoxLander__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBotoxLander__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "CadmenPRPLander";
  } else {
    func.displayName = `CadmenPRPLander.${nodeName}`;
  }
  return func;
}

export const CadmenPRPLander = Object.assign(
  // Top-level CadmenPRPLander renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topNav: makeNodeComponent("topNav"),
    hero: makeNodeComponent("hero"),
    heroButton: makeNodeComponent("heroButton"),
    heroImage: makeNodeComponent("heroImage"),
    threeCardsSection: makeNodeComponent("threeCardsSection"),
    threeCards: makeNodeComponent("threeCards"),
    chooseBotoxSection: makeNodeComponent("chooseBotoxSection"),
    chooseBotoxHeader: makeNodeComponent("chooseBotoxHeader"),
    peopleChooseNav: makeNodeComponent("peopleChooseNav"),
    chooseBotoxPoints: makeNodeComponent("chooseBotoxPoints"),
    chooseBotoxDot2: makeNodeComponent("chooseBotoxDot2"),
    chooseBotoxDot3: makeNodeComponent("chooseBotoxDot3"),
    chooseBotoxDot4: makeNodeComponent("chooseBotoxDot4"),
    chooseBotoxButton: makeNodeComponent("chooseBotoxButton"),
    chooseBotoxImages: makeNodeComponent("chooseBotoxImages"),
    button: makeNodeComponent("button"),
    howBotoxWorksSection: makeNodeComponent("howBotoxWorksSection"),
    howBotoxWorksHeader: makeNodeComponent("howBotoxWorksHeader"),
    howBotoxWorksCards: makeNodeComponent("howBotoxWorksCards"),
    howBotoxWorksCardsMobile: makeNodeComponent("howBotoxWorksCardsMobile"),
    areasInteractive: makeNodeComponent("areasInteractive"),
    beforeAfterSection: makeNodeComponent("beforeAfterSection"),
    beforeAfterHeader: makeNodeComponent("beforeAfterHeader"),
    beforeAfterSlider: makeNodeComponent("beforeAfterSlider"),
    botoxHelpedSection: makeNodeComponent("botoxHelpedSection"),
    botoxHelpedScroller: makeNodeComponent("botoxHelpedScroller"),
    satisfiedClientsSlider: makeNodeComponent("satisfiedClientsSlider"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    videoCtaButton: makeNodeComponent("videoCtaButton"),
    ourLocationSection: makeNodeComponent("ourLocationSection"),
    specialOfferButton: makeNodeComponent("specialOfferButton"),
    footerNew: makeNodeComponent("footerNew"),
    claimBotoxFooter: makeNodeComponent("claimBotoxFooter"),
    // Metadata about props expected for CadmenPRPLander
    internalVariantProps: PlasmicBotoxLander__VariantProps,
    internalArgProps: PlasmicBotoxLander__ArgProps,
    // Page metadata
    // pageMetadata: {
    //   title: `CadmenClinic | ${args.serviceData.general.shortTitle}`,
    //   description: "",
    //   ogImageSrc: "",
    //   canonical: ""
    // }
  }
);

export default CadmenPRPLander;
/* prettier-ignore-end */
