// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fpxTiFS69ULcX4wDGEfw3c
// Component: Npe59kGyeDl0
import * as React from "react";
import Head from "next/head";
import Link from 'next/link';
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateStateOnChangeProp,
  generateStateValueProp,
  hasVariant,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import TopNav from "../../TopNav"; // plasmic-import: xBvtLE-eO4gb/component
import Button from "../../Button"; // plasmic-import: 0o-OkGmTYJg3/component
import ReviewsRatingPill from "../../ReviewsRatingPill"; // plasmic-import: lUTkTuQcsEcx/component
import BenefitsOfBotoxCard from "../../BenefitsOfBotoxCard"; // plasmic-import: NylQq7mzP_E5/component
import TestimonialsSlider from "@/components/TestimonialsSlider/TestimonialsSlider"; // plasmic-import: J0SSSRogRoTR/codeComponent
import TestimonialCard from "../../TestimonialCard"; // plasmic-import: zWVJ2Qd7n2nR/component
import TextToggler from "../../TextToggler"; // plasmic-import: nk356y6CCF9w/component
import BotoxProcessCard from "../../BotoxProcessCard"; // plasmic-import: 7fDdA2kY52_t/component
import AffordableBotoxCard from "../../AffordableBotoxCard"; // plasmic-import: dCCKAyC8oXyh/component
// import FaceSection from "../../FaceSection"; // plasmic-import: dOVgE0OgS0yG/component
import AreasInteractive from "../../AreasInteractive"; // plasmic-import: cNLJfmXsSSOr/component
import BotoxResultCard from "../../BotoxResultCard"; // plasmic-import: LkkGmqnkkLRj/component
import SelectPill from "../../SelectPill"; // plasmic-import: XgOD49Zg0vP7/component
import HowItWorksCard from "../../HowItWorksCard"; // plasmic-import: w7EJDoU6NMVc/component
import AgeGroupsCard from "../../AgeGroupsCard"; // plasmic-import: 0IByburiocI3/component
import IconLayeredCircles from "../../IconLayeredCircles"; // plasmic-import: otc6Jw_feodx/component
import Faq from "../../Faq"; // plasmic-import: kXqZTEGKWOeX/component
import BotoxMythsSlider from "@/components/BotoxMythsSlider/BotoxMythsSlider"; // plasmic-import: 7M8CJgEEKvIi/codeComponent
import BotoxMythsCard from "../../BotoxMythsCard"; // plasmic-import: 4aj6TPf-GBTB/component
import OurLocationSection from "../../OurLocationSection"; // plasmic-import: 90jT_0Y9mL-p/component
import FooterNew from "../../FooterNew"; // plasmic-import: NE5t6IteXed-/component
import { useScreenVariants as useScreenVariants_4IUcgkiijTv2 } from "../blank_website/PlasmicGlobalVariant__Screen"; // plasmic-import: 4iUCGKIIJTv2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../blank_website/plasmic.module.css"; // plasmic-import: fpxTiFS69ULcX4wDGEfw3c/projectcss
import sty from "./PlasmicBotoxSeo.module.css"; // plasmic-import: Npe59kGyeDl0/css
import TimeSvgIcon from "./icons/PlasmicIcon__TimeSvg"; // plasmic-import: zfqY32R6mG7W/icon
import Face2SvgIcon from "./icons/PlasmicIcon__Face2Svg"; // plasmic-import: na4dw5YDiVRa/icon
import HeartSvg3Icon from "./icons/PlasmicIcon__HeartSvg3"; // plasmic-import: Y1Pl_F2w77Si/icon
import TimeSvg3Icon from "./icons/PlasmicIcon__TimeSvg3"; // plasmic-import: ncO_R5hfk1Yu/icon
import IconFace2Icon from "./icons/PlasmicIcon__IconFace2"; // plasmic-import: XXHGqwEaOKMh/icon
import HeartSvg4Icon from "./icons/PlasmicIcon__HeartSvg4"; // plasmic-import: QQ0zzfq_LES4/icon
import PointIcon from "./icons/PlasmicIcon__Point"; // plasmic-import: dMjm7kjmXw_d/icon

import RatingReviewPill from "@/components/RatingReviewPill";
import AffordableHairRestoration from "@/components/AffordableHairRestoration";
import HairLandingHero from "@/components/HairLandingHero";
import WhyOurPatientsSlider from "@/components/WhyOurPatientsSlider/WhyOurPatientsSlider";
import AlternatingInfoCard from "@/components/AlternatingInfoCard/AlternatingInfoCard";

import { useWindowSize } from 'react-use'
import VideoSection from "@/components/VideoSection/VideoSection";
import TreatmentPackagesSlider from "@/components/TreatmentPackagesSlider/TreatmentPackagesSlider";
import CadmenOurProcess from "./CadmenOurProcess";
import CadmenPreparingForAppointment from "./CadmenPreparingForAppointment";

createPlasmicElementProxy;

export const PlasmicBotoxLander2__VariantProps = new Array();

export const PlasmicBotoxLander2__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBotoxLander2__RenderFunc(props) {
  const beforeAfters = [
    {
        id: 1,
        title: "Jacob’s Results",
        subtitle: "Results after 4 PRP Sessions",
        img: "/media/testimonials/Jacob.jpg"
    },
    {
        id: 2,
        title: "Amy’s Results",
        subtitle: "Results after 3 Exosome and 6 Meso Sessions",
        img: "/media/testimonials/Amy.jpg"
    },
    {
        id: 3,
        title: "Nithin’s Results",
        subtitle: "Results after 3 Exosome Sessions",
        img: "/media/testimonials/Nithin.jpg"
    },
    {
        id: 4,
        title: "Anna’s Results",
        subtitle: "Results after 3 PRP Sessions",
        img: "/media/testimonials/Anna.jpg"
    },
    {
        id: 5,
        title: "Brandon’s Results",
        subtitle: "Results after 3 PRP and 3 Exosome Sessions",
        img: "/media/testimonials/Brandon.jpg"
    },
    {
        id: 6,
        title: "Ritu’s Results",
        subtitle: "Results after 6 Mesotherapy Sessions",
        img: "/media/testimonials/Ritu.jpg"
    },
    {
        id: 7,
        title: "Ron’s Results",
        subtitle: "Results after 6 Mesotherapy Sessions",
        img: "/media/testimonials/Ron.jpg"
    },
    {
        id: 8,
        title: "Michael's Results",
        subtitle: "Results after 6 PRP Sessions",
        img: "/media/testimonials/Michael.jpg"
    },
    {
        id: 9,
        title: "Nick's Results",
        subtitle: "Results after 6 Exosome Sessions",
        img: "/media/testimonials/Nick.jpg"
    },
  ];
  const treatmentPackages = [
    {
      id: 1,
      title: "4 PRP Hair Restoration",
      specialPrice: "$1,799",
      regularPrice: "$2,399",
      items: [
        {
          title: "7-Week Program to Re-Grow Your Hair",
          description: "Treatments scheduled every 2 weeks to ensure optimal results"
        }, 
        {
          title: "Ideal for patients seeking to effectively stimulate natural hair growth to combat ongoing hair loss, shedding, and thinning"
        }
      ]
    },
    {
      id: 2,
      title: "3 Exosome Hair Therapy",
      specialPrice: "$1,799",
      regularPrice: "$2,399",
      items: [
        {
          title: "7-Week Program to Prevent Hair Loss",
          description: "Treatments scheduled every 2 weeks to ensure optimal results"
        }, 
        {
          title: "Ideal for patients seeking to address the root cause of hair loss and stimulate hair growth by blocking DHT levels and leverage powerful growth factors"
        }
      ]
    }, 
    {
      id: 3,
      title: "6 Mesotherapy Vitamin",
      specialPrice: "$1,999",
      regularPrice: "$2,399",
      items: [
        {
          title: "11-Week Program to Nourish Scalp & Prevent Loss",
          description: "Treatments scheduled every 2 weeks to ensure optimal results"
        }, 
        {
          title: "Ideal for patients seeking a healthier and nourished scalp while combatting hair loss through blocking DHT levels and stimulating new follicle growth"
        }
      ]
    }, 
    {
      id: 4,
      title: "3 PRP + \n3 Exosome",
      specialPrice: "$3,099",
      regularPrice: "$4,199",
      items: [
        {
          title: "11-Week Program to Re-Grow Your Hair and Prevent Further Hair Loss",
          description: "Treatments scheduled every 2 weeks to ensure optimal results"
        }, 
        {
          title: "Our BEST-SELLING package for anyone seeking the full solution – re-grow your hair while blocking DHT to prevent further hair loss"
        }
      ]
    }, 
    {
      id: 5,
      title: "3 PRP + \n6 Mesotherapy",
      specialPrice: "$2,999",
      regularPrice: "$4,199",
      items: [
        {
          title: "9-Week Program to Re-Grow Your Hair and Nourish Your Scalp with Essential Vitamins & Growth Factors",
          description: "Treatments scheduled every 1 week for optimal result"
        }, 
        {
          title: "Ideal for patients seeking optimal results for new hair growth – a nourished scalp throughout your PRP process increases longevity of your results"
        }
      ]
    }, 
    {
      id: 6,
      title: "3 Exosome + \n6 Mesotherapy",
      specialPrice: "$3,499",
      regularPrice: "$4,799",
      items: [
        {
          title: "9-Week Program to Re-Grow Your Hair, Prevent Further Hair Loss, and Nourish Your Scalp",
          description: "Treatments scheduled every 1 week for optimal result"
        }, 
        {
          title: "Curated for patients ineligible for PRP Hair Restoration, pair Exosome Hair Therapy with Mesotherapy Vitamins to unlock powerful results"
        }
      ]
    }, 
  ];
  const section8cards = [
    {
      id: 1,
      icon: "verified",
      img: "/media/services/prp/3.1.jpg",
      title: "We ONLY Offer Proven and Effective Hair Restoration Treatments",
      description: "When it comes to hair restoration, clients choose CADMEN Clinic for our commitment to quality, safety, and exception results. Let’s explore what sets CADMEN Clinic apart and why so many clients consider us the go-to for natural hair restoration.",
      points: [
        {
          heading: "Expertise & Precision of Our Skilled Injections"
        },
        {
          heading: "Comprehensive Consultation Process"
        },
        {
          heading: "State-of-the-Art Facility"
        },
        {
          heading: "Commitment to Safety & Quality" 
        },
        {
          heading: "Transparent Pricing"
        }
      ]
    },
    {
      id: 2,
      icon: "sparkle",
      img: "/media/hair-landing/4.jpg",
      title: "Real Client Transformations",
      description: "We're proud of the incredible transformations our clients achieve with our treatments, and our before-and-after gallery showcases the natural, impactful results our injectors create. By addressing each client's unique hair goals and concerns, we're able to deliver outcomes that exceed expectations.",
      points: [
        {
          heading: "Before and After Gallery",
          subheading: "Our gallery features real clients who have achieved exceptional hair re-growth and prevented further hair loss."
        },
        {
          heading: "Client Testimonials",
          subheading: "Many clients leave glowing testimonials about their experiences, highlighting the professionalism, care, and expertise of our team."
        }
      ]
    },
    {
      id: 3,
      icon: "portrait",
      img: "/media/services/prp/7.1.jpg",
      title: "Expertise and Precision of Our Skilled Injectors",
      description: "At CADMEN Clinic, hair restoration treatments are administered by experienced, licensed injectors who specialize in hair growth. Our injectors have extensive training in hair and advanced injection techniques, ensuring that every treatment is both safe and precisely tailored to your unique features.",
      points: [
        {
          heading: "Personalized Approach",
          subheading: "Our injectors take the time to understand your goals, whether you're looking for a subtle refresh or a more dramatic improvement."
        },
        {
          heading: "Natural Results",
          subheading: "We prioritize a natural look, only offering 100% natural treatments to give you the highest-quality result."
        },
        {
          heading: "Experienced Team",
          subheading: "With years of experience in cosmetic injectables, our team has a deep understanding of how to customize our treatments for each client's needs."
        }
      ]
    },
    {
      id: 4,
      icon: "headset",
      img: "/media/hair-landing/6.jpg",
      title: "Comprehensive Consultation Process",
      description: "We believe that a successful hair restoration experience starts with a thorough consultation. During your initial appointment, we take the time to assess your scalp, discuss your hair goals, and explain our treatments in detail. This personalized approach helps us create a treatment plan tailored to your needs.",
      points: [
        {
          heading: "Detailed Assessment",
          subheading: "We analyze your hair type, scalp, and specific concerns to ensure which hair restoration treatment is right for you."
        },
        {
          heading: "Goal-Setting",
          subheading: "Our team works with you to establish realistic goals and answer any questions, so you feel confident and informed."
        },
        {
          heading: "Transparent Communication",
          subheading: "We explain all aspects of the procedure, from the expected results to post-care and maintenance."
        }
      ]
    },
    {
      id: 5,
      icon: "heart",
      img: "/media/hair-landing/7.jpg",
      title: "State-of-the-Art Facility and \nComfort-Focused Experience",
      description: "Our medspa is designed to provide a relaxing and luxurious experience from the moment you walk in. We use advanced tools and techniques to deliver the highest level of care in a clean, modern, and comfortable environment.",
      points: [
        {
          heading: "Advanced Technology",
          subheading: "Our facility is equipped with cutting-edge tools that enhance the hair restoration experience, ensuring precise and effective treatments."
        },
        {
          heading: "Client-Centered Atmosphere",
          subheading: "We prioritize comfort and confidentiality, creating an environment where clients feel at ease."
        },
        {
          heading: "Safety Standards",
          subheading: "We adhere to the highest safety protocols to ensure a safe experience with every visit."
        }
      ]
    },
    {
      id: 6,
      icon: "syringe",
      img: "/media/services/prp/4.1.jpg",
      title: "Commitment to Safety and Quality",
      description: "Safety is a top priority at CADMEN Clinic. Our injectors follow strict safety protocols, and we only use approved solutions from trusted manufacturers. With our commitment to the highest standards, you can rest assured that you're in safe, professional hands.",
      points: [
        {
          heading: "Certified Providers",
          subheading: "Our team is fully certified in Botox administration, ensuring that each injector has the skills and knowledge required to deliver safe and effective treatments."
        },
        {
          heading: "Health Canada-Approved Product",
          subheading: "We use authentic, Health Canada-approved solutions to provide you with the best and safest results."
        },
        {
          heading: "Stringent Protocols",
          subheading: "From sterilization to injection techniques, we follow rigorous protocols to ensure your safety and satisfaction."
        }
      ]
    },
    {
      id: 7,
      icon: "moneybag",
      img: "/media/hair-landing/9.jpg",
      title: "Transparent Pricing",
      description: "At CADMEN Clinic, we believe in clear, upfront pricing for all of our services. Our clients appreciate knowing exactly what to expect in terms of cost, with no hidden fees. Plus, we offer a membership program to reward our clients for their continued trust in us.",
      points: [
        {
          heading: "Transparent Pricing",
          subheading: "Our pricing is straightforward, and we're happy to provide an estimate during your consultation."
        },
        {
          heading: "Exclusive Discounts",
          subheading: "New patients receive <strong>50% off their first treatment and exclusive package discounts</strong>."
        }
      ]

    }
  ];

  const { width: windowWidth, height: windowHeight } = useWindowSize();
  
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "selectedArea",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "Forehead"
      },
      {
        path: "areasList",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            name: "Forehead",
            range: "$100 - $200",
            units: "10-20 units",
            face_dot: { left: "51.5%", top: "10%" }
          },
          {
            name: "Brow Lift",
            range: "$50 - $100",
            units: "5-10 units",
            face_dot: { left: "67%", top: "22%" }
          },
          {
            name: "Crow's Feet",
            range: "$50 - $150",
            units: "5-15 units",
            face_dot: { left: "75%", top: "37%" }
          },
          {
            name: "11'S",
            range: "$200 - $300",
            units: "20-30 units",
            face_dot: { left: "51.5%", top: "27%" }
          },
          {
            name: "Nasolabial Folds",
            range: "$50 - $100",
            units: "5-10 units",
            face_dot: { left: "36%", top: "61%" }
          },
          {
            name: "Gummy Smile",
            range: "$100",
            units: "Varies",
            face_dot: { left: "49%", top: "65%" }
          },
          {
            name: "Lip Flip",
            range: "$125",
            units: "Varies",
            face_dot: { left: "58%", top: "73%" }
          },
          {
            name: "Chin Dimpling",
            range: "$40 - $100",
            units: "4-10 units",
            face_dot: { left: "51.5%", top: "91%" }
          },
          {
            name: "Masseter",
            range: "$200 - $400",
            units: "20-40 units",
            face_dot: { left: "65%", top: "63%" }
          }
        ]
      },
      {
        path: "botoxResultsList",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            title: "Metabolism",
            description:
              "People with faster metabolisms may find that their Botox wears off quicker.",
            icon: "/plasmic/image_lab_2024/images/icon-person2.svg",
            image: "/plasmic/image_lab_2024/images/image26.jpg"
          },
          {
            title: "Treatment Area",
            description:
              "Areas with larger muscles, such as the jaw, may break down Botox more quickly.",
            icon: "/plasmic/image_lab_2024/images/icon-person.svg",
            image: "/plasmic/image_lab_2024/images/image38.jpg"
          },
          {
            title: "Aftercare and Lifestyle",
            description:
              "Avoiding intense exercise, sun exposure & facial massages immediately after treatment can help prolong results.",
            icon: "/plasmic/image_lab_2024/images/icon-heart.svg",
            image: "/plasmic/image_lab_2024/images/imagePng57.png"
          }
        ]
      },
      {
        path: "botoxResultArea",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "Metabolism"
      },
      {
        path: "ageGroupsList",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            years: "20 years",
            title: "Botox in Your 20s: Preventative Measures",
            description:
              "In your 20s, you may not yet see prominent wrinkles or lines, but subtle changes often begin around this age. Many people start with preventative Botox, targeting areas where dynamic lines\u2014caused by repeated facial movements\u2014are beginning to form. The goal of preventative Botox is to prevent lines from becoming deeply etched in the skin as you age.",
            items: [
              {
                title: "Common Treatment Areas:",
                description:
                  "Forehead lines, frown lines between the brows (glabellar lines), and crow\u2019s feet."
              },
              {
                title: "Benefits:",
                description:
                  "Botox helps minimize the formation of fine lines before they settle into deeper wrinkles, preserving a smooth complexion."
              },
              {
                title: "Fun Fact:",
                description:
                  "Preventative Botox doesn\u2019t mean you won\u2019t need Botox later; it just means you may need it less frequently or in smaller doses as you age."
              }
            ]
          },
          {
            years: "30 years",
            title: "Botox in Your 30s: Early Treatment for Fine Lines",
            description:
              "By your 30s, fine lines may have started to develop, especially if you're prone to frequent expressions like squinting or frowning. Botox treatments at this age are focused on smoothing out these early signs of aging while preventing them from getting deeper.",
            items: [
              {
                title: "Common Treatment Areas:",
                description:
                  "The forehead, between the eyebrows, and around the eyes."
              },
              {
                title: "Benefits:",
                description:
                  "Botox at this stage can reduce the appearance of existing fine lines and provide a smoother, refreshed look. Regular treatments can help maintain this youthful appearance."
              },
              {
                title: "Fun Fact:",
                description:
                  "Many people in their 30s find that Botox every 3-6 months gives the best results, depending on how quickly their body metabolizes the product."
              }
            ]
          },
          {
            years: "40 years",
            title: "Botox in Your 40s: Managing Dynamic and Static Wrinkles",
            description:
              "In your 40s, Botox can address more pronounced wrinkles, often caused by years of repeated expressions and sun exposure. While some wrinkles may have settled in, Botox can still soften these lines, giving you a more youthful look.",
            items: [
              {
                title: "Common Treatment Areas:",
                description:
                  "Dynamic wrinkles (those visible when moving your face) around the eyes, forehead, and mouth, as well as some static wrinkles that are visible at rest."
              },
              {
                title: "Benefits:",
                description:
                  "By targeting dynamic wrinkles, Botox can help reduce their prominence. Additionally, Botox may be paired with other treatments, like dermal fillers, to provide a fuller rejuvenation effect for static lines."
              },
              {
                title: "Fun Fact:",
                description:
                  "Many clients in their 40s opt for Botox every 3-4 months to maintain results."
              }
            ]
          },
          {
            years: "50 years",
            title: "Botox in Your 50s and Beyond Smoothing Deep Lines",
            description:
              "In your 50s and beyond, Botox can still provide beautiful results, often as part of a larger anti-aging regimen. At this stage, Botox is commonly combined with other aesthetic treatments, such as dermal fillers or laser therapies, to address deeper lines and overall skin laxity.",
            items: [
              {
                title: "Common Treatment Areas:",
                description:
                  "Areas with deeper wrinkles, such as the forehead, around the eyes, and near the mouth."
              },
              {
                title: "Benefits:",
                description:
                  "Botox in these areas helps to reduce the appearance of deep lines, and when paired with other treatments, it can create a lifted, youthful look."
              },
              {
                title: "Recommended Approach:",
                description:
                  "A combination of Botox, fillers, and possibly laser treatments can work synergistically to provide natural and comprehensive facial rejuvenation."
              }
            ]
          }
        ]
      },
      {
        path: "ageGroupsArea",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "20 years"
      },
      {
        path: "areasInteractive.data",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            name: "Forehead",
            range: "$100 - $200",
            units: "10-20 units",
            face_dot: { left: "51.5%", top: "10%" }
          },
          {
            name: "Brow Lift",
            range: "$50 - $100",
            units: "5-10 units",
            face_dot: { left: "67%", top: "22%" }
          },
          {
            name: "Crow's Feet",
            range: "$50 - $150",
            units: "5-15 units",
            face_dot: { left: "75%", top: "37%" }
          },
          {
            name: "11'S",
            range: "$200 - $300",
            units: "20-30 units",
            face_dot: { left: "51.5%", top: "27%" }
          },
          {
            name: "Nasolabial Folds",
            range: "$50 - $100",
            units: "5-10 units",
            face_dot: { left: "36%", top: "61%" }
          },
          {
            name: "Gummy Smile",
            range: "$100",
            units: "Varies",
            face_dot: { left: "49%", top: "65%" }
          },
          {
            name: "Lip Flip",
            range: "$125",
            units: "Varies",
            face_dot: { left: "58%", top: "73%" }
          },
          {
            name: "Chin Dimpling",
            range: "$40 - $100",
            units: "4-10 units",
            face_dot: { left: "51.5%", top: "91%" }
          },
          {
            name: "Masseter",
            range: "$200 - $400",
            units: "20-40 units",
            face_dot: { left: "65%", top: "63%" }
          }
        ]
      },
      {
        path: "areasInteractive.selected",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "Forehead"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_4IUcgkiijTv2()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicBotoxLander2.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicBotoxLander2.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicBotoxLander2.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      {/* 1. hero page */}
      <HairLandingHero/>


      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >

          
          
          {/* 2. before after section */}
          <section
            data-plasmic-name={"beforeAfterSection"}
            data-plasmic-override={overrides.beforeAfterSection}
            className={classNames(projectcss.all, sty.beforeAfterSection)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"beforeAfterHeader"}
              data-plasmic-override={overrides.beforeAfterHeader}
              hasGap={true}
              className={classNames(projectcss.all, sty.beforeAfterHeader)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__vb63O
                )}
              >
                <React.Fragment>
                  <React.Fragment>{"Before & "}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      fontStyle: "italic",
                      fontWeight: 500,
                      color: "#D19D51"
                    }}
                  >
                    {"After"}
                  </span>
                </React.Fragment>
              </h2>
              <p
                className={classNames(
                  projectcss.all,
                  projectcss.p,
                  projectcss.__wab_text,
                  sty.p__zTptG
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "The results of our clients speak for themselves"
                  : "The results of our clients speak for themselves"}
              </p>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__veMx)}>
              <TestimonialsSlider
                data-plasmic-name={"beforeAfterSlider"}
                data-plasmic-override={overrides.beforeAfterSlider}
                className={classNames("__wab_instance", sty.beforeAfterSlider)}
                ctaLink={"#"}
                ctaText={"Act Now"}
                isDarkBg={false}
                settings={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? {
                        dots: false,
                        arrows: false,
                        infinite: true,
                        speed: 500,
                        slidesToShow: 1,
                        slidesToScroll: 1
                      }
                    : hasVariant(globalVariants, "screen", "midsize")
                    ? {
                        dots: false,
                        arrows: false,
                        infinite: true,
                        speed: 500,
                        slidesToShow: 2,
                        slidesToScroll: 1
                      }
                    : {
                        dots: false,
                        arrows: false,
                        infinite: true,
                        speed: 500,
                        slidesToShow: 3,
                        slidesToScroll: 1
                      }
                }
              >
                {beforeAfters.map((beforeAfter) => (
                  <TestimonialCard
                    className={classNames(
                      "__wab_instance",
                      sty.testimonialCard__rFqgo
                    )}
                    id={beforeAfter.id}
                    subtitle={beforeAfter.subtitle}
                    title={beforeAfter.title}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2Nkey)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: beforeAfter.img,
                        fullWidth: 486,
                        fullHeight: 480,
                        aspectRatio: undefined
                      }}
                    />
                  </TestimonialCard>
                ))}
              </TestimonialsSlider>
            </div>
          </section>

          {/* 3. affordable hair restoration treatments tailored to you */}
          <Stack__
            as={"section"}
            data-plasmic-name={"affordableBotoxSection"}
            data-plasmic-override={overrides.affordableBotoxSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.affordableBotoxSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1JzFp)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fLnGd
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#080909" }}
                    >
                      {"Affordable"}
                    </span>
                    <React.Fragment>{"\n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#080909" }}
                    >
                      {"Hair Restoration Treatments"}
                    </span>
                    <React.Fragment> </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#9a7f71", fontStyle: "italic" }}
                    >
                      {"Tailored to You"}
                    </span>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#080909" }}
                    >
                      {"Affordable Hair Restoration"}
                    </span>
                    <br></br>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#080909" }}
                    >
                      {"Treatments "}
                    </span>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#9a7f71", fontStyle: "italic" }}
                    >
                      {"Tailored to You"}
                    </span>
                  </React.Fragment>
                )}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tfw7
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#535556" }}
                  >
                    {
                      "Affordable, transparent Hair Restoration pricing tailored to your goals and budget."
                    }
                  </span>
                </React.Fragment>
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__hib93)}
            >
              {/* PRP Hair Restoration */}
              <AffordableBotoxCard
                name={"PRP Hair Restoration"}
                link={"/services/hair-restoration/prp"}
                perUnit={"$599"}
                price={"$299"}
                className={classNames(
                  "__wab_instance",
                  sty.affordableBotoxCard__v1OXt
                )}
                items={
                  [
                    {
                      title: "Stimulate New Hair Growth",
                      description:
                        "Use your own body’s plasma to boost hair growth in targeted regions"
                    },
                    {
                      title: "Clinically Backed, Proven Results",
                      description:
                        "The most studied natural hair restoration service – 100% natural, no chemicals or foreign substances"
                    },
                    {
                      title: "Over 7,000 Treatments Performed at CADMEN",
                      description:
                        "We are the only clinic in Ontario with medical-grade PRP Hair Restoration practices, we laser-focused on results to ensure spectacular results"
                    }
                  ]
                }
              />

              {/* Exosome Hair Therapy */}
              <AffordableBotoxCard
                name={"Exosome Hair Therapy"}
                link={"/services/hair-restoration/exosomes"}
                perUnit={"$799"}
                price={"$399"}
                className={classNames(
                  "__wab_instance",
                  sty.affordableBotoxCard___844NL
                )}
                items={[
                  {
                    title: "Stop Further Hair Thinning and Shedding",
                    description:
                      "Address the root cause of your hair loss by blocking DHT on your scalp"
                  },
                  {
                    title: "Stimulate Rapid Hair Growth",
                    description:
                      "Activate healing dormant hair follicles to stimulate new hair growth faster driven by the powerful growth vectors in our propriety solution"
                  },
                  {
                    title: "Next-Gen Regenerative Science",
                    description:
                      "Our stem cell-derived proprietary Exosomes solution has disrupted the industry due to its unparallelled levels of efficacy"
                  }
                ]}
              />

              {/* Mesotherapy Vitamins */}
              <AffordableBotoxCard
                name={"Mesotherapy Vitamins"}
                link={"/services/hair-restoration/mesotherapy"}
                perUnit={"$399"}
                price={"$199"}
                className={classNames(
                  "__wab_instance",
                  sty.affordableBotoxCard__rVlvw
                )}
                items={[
                  {
                    title: "Strengthen Thinning Hair",
                    description:
                      "Nourish your scalp from the root up to prevent further hair loss"
                  },
                  {
                    title: "Improve Scalp Circulation for Hair Growth",
                    description:
                      "Microinjections of complex vitamins boost blood circulation in your scalp while providing nutrients required to stimulate hair growth"
                  },
                  {
                    title: "Clinically Proven Ingredients",
                    description:
                      "Complex blend of amino acids, vitamins, DHT blocker, and other essential nutrients that are dermatologist backed and tested with precision"
                  }
                ]}
              />
            </Stack__>

            <Link href='/book-now'  className='mt-[10px] w-full md:w-auto'>
              <button className='button w-full md:w-auto'>Book Now</button>
            </Link>
          </Stack__>

          {/* 4. afforadble prices interactive section (import) */}
          <AffordableHairRestoration/>

          {/* 5. Proven & Affordable Treatment Packages Tailored for All Types of Hair Loss (slider) */}
          <Stack__
            as={"section"}
            data-plasmic-name={"affordableBotoxSection"}
            data-plasmic-override={overrides.affordableBotoxSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.affordableBotoxSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1JzFp)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fLnGd
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#080909" }}
                  >
                    {"Proven & Affordable Treatment Packages"}
                  </span>
                  <React.Fragment>{"\n"}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#080909" }}
                  >
                    {"Tailored for"}
                  </span>
                  <React.Fragment> </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#9a7f71", fontStyle: "italic" }}
                  >
                    {"All Types of Hair Loss"}
                  </span>
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tfw7
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#535556" }}
                  >
                    {"Discounted packages tailored for your goals and budget. Schedule a free consultation to figure out which package is for you."}
                  </span>
                </React.Fragment>
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__hib93)}
            >
            <TreatmentPackagesSlider treatmentPackages={treatmentPackages} />

            </Stack__>
          </Stack__>

          {/* 6. our hair restoration program */}
          <CadmenOurProcess 
            title="Hair Restoration"
            program=" Program"
            consultation="Begin with a personalized consultation where our experts assess your hair and discuss your goals. We’ll create a tailored treatment plan to ensure optimal results that align with your needs."
            treatment="During your hair restoration session, a skilled practitioner will administer precise injections and/or microneedling to targeted areas. The procedure is quick, minimally invasive, and designed for your comfort."
            results="Enjoy thicker, fuller hair while significantly reducing hair loss with our proven treatments. With minimal downtime, you’ll look refreshed and confident in no time."
          />

          {/* 7. Preparing for your hair restoration appointment */}
          <CadmenPreparingForAppointment />
          <Stack__
            as={"section"}
            data-plasmic-name={"botoxAppointmentSection"}
            data-plasmic-override={overrides.botoxAppointmentSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.botoxAppointmentSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___14QN)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__hhfus)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___4V7A8)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zXpNv
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "midsize") ? (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#080909" }}
                        >
                          {"Preparing for Your"}
                        </span>
                        <React.Fragment> </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#D19D51" }}
                        >
                          {"Hair Restoration Appointment"}
                        </span>
                      </React.Fragment>
                    ) : (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#080909" }}
                        >
                          {"Preparing for Your"}
                        </span>
                        <React.Fragment> </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#D19D51" }}
                        >
                          {"Hair Restoration Appointment"}
                        </span>
                      </React.Fragment>
                    )}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__k235L
                    )}
                  >
                    {"Here are some tips to ensure a smooth experience:"}
                  </div>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___87Pse)}
                >
                  {/* stay adequately hydrated */}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eqIOp)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"title"}
                      data-plasmic-override={overrides.title}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.title)}
                    >
                      <PointIcon
                        className={classNames(projectcss.all, sty.svg__tNu1F)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a1TXf
                        )}
                      >
                        {"Stay Adequately Hydrated"}
                      </div>
                    </Stack__>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Xz0B
                      )}
                    >
                      {"During the day of your appointment, stay hydrated to ensure optimal results. For PRP Hair Restoration, we advise patients to be sufficiently hydrated to ensure an ample amount of blood can be drawn."}
                    </div>
                  </div>

                  {/* skip alcohol and tobacco */}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__p9P7X)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"title2"}
                      data-plasmic-override={overrides.title2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.title2)}
                    >
                      <PointIcon
                        className={classNames(projectcss.all, sty.svg___6AfnD)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gvoCy
                        )}
                      >
                        {"Skip Alcohol and Tobacco"}
                      </div>
                    </Stack__>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___24Kjb
                      )}
                    >
                      {
                        "Both can increase bruising and affect your skin\u2019s recovery. Try to avoid alcohol for at least 24 hours before and after treatment."
                      }
                    </div>
                  </div>

                  {/* inform your provider of medical history */}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qJgGy)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"title3"}
                      data-plasmic-override={overrides.title3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.title3)}
                    >
                      <PointIcon
                        className={classNames(projectcss.all, sty.svg__xjPsH)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4O0
                        )}
                      >
                        {"Inform Your Provider of Medical History"}
                      </div>
                    </Stack__>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__n0Hkk
                      )}
                    >
                      {
                        "Be transparent about any medical conditions, allergies, or medications you\u2019re taking. This information helps us customize your treatment and prevent potential complications."
                      }
                    </div>
                  </div>
                </Stack__>
              </Stack__>

              <Link href='/book-now'  className='mt-[10px] w-full md:w-auto'>
                <button className='button w-full md:w-auto'>Book Now</button>
              </Link>

            
            {/* image section for "preparing for your hair restoration appointment " */}
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ch388)}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__m5RlW)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "200px"
                    : hasVariant(globalVariants, "screen", "midsize")
                    ? "100%"
                    : "641px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "100%"
                    : "641px"
                }
                loading={"lazy"}
                src={{
                  src: "/media/services/prp/4.4.jpg",
                  fullWidth: 1300,
                  fullHeight: 1115,
                  aspectRatio: undefined
                }}
                style={{ height: "641px", width: "100%", objectFit: "cover" }}
              />
            </Stack__>
          </Stack__>

          {/* 8. What to expect during and after the treatment */}
          <Stack__
            as={"section"}
            data-plasmic-name={"afterTheTreatmentSection"}
            data-plasmic-override={overrides.afterTheTreatmentSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.afterTheTreatmentSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__avtMx)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__pM6Cj)}
                // displayHeight={
                //   hasVariant(globalVariants, "screen", "midsize")
                //     ? "100%"
                //     : "auto"
                // }
                displayHeight={
                  hasVariant(globalVariants, "screen", "midsize") ? "300px" : "auto"
                }
                displayWidth="100%"
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/media/hair-landing/2.jpg",
                  fullWidth: 1300,
                  fullHeight: 1423,
                  aspectRatio: undefined
                }}
                style={{ height: "auto", width: "100%", objectFit: "cover" }}
              />
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__fBcEx)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jyaYg)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xXnt1)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__io7Fa
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#080909" }}
                      >
                        {"What to Expect"}
                      </span>
                      <React.Fragment> </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#D19D51" }}
                      >
                        {"During and After "}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#080909" }}
                      >
                        {"the Treatment"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wQcHr
                    )}
                  >
                    {"Our hair restoration treatments are minimally invasive and quick, typically taking 30 minutes. Most patients describe the feeling as a slight pinch on your scalp."}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xk3C)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9EBfz
                    )}
                  >
                    {"Post-Treatment Care:"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__pqLf)}
                  >
                    <PointIcon
                      className={classNames(projectcss.all, sty.svg___4KuWw)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0Op2E
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#535556" }}
                        >
                          {"Avoid showering and applying any hair products for at least 24 hours post-treatment to ensure full efficacy."}
                        </span>
                      </React.Fragment>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__j0AL)}
                  >
                    <PointIcon
                      className={classNames(projectcss.all, sty.svg___5Xh4E)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gyFvG
                      )}
                    >
                      {"Stay hydrated throughout the day to support healing – this is recommended especially after PRP and Exosome treatments."}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__n3Sx)}
                  >
                    <PointIcon
                      className={classNames(projectcss.all, sty.svg__dvNar)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zuWu4
                      )}
                    >
                      {"Protect your scalp from direct sun exposure for atleast 24 hours."}
                    </div>
                  </Stack__>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bx3Iz
                  )}
                >
                  {"Results typically begin to appear within 2-3 sessions, however it is critical to follow our post-treatment care to ensure you are getting optimal results."}
                </div>
              </Stack__>

              <Link href='/book-now'  className='mt-[10px] w-full md:w-auto'>
                <button className='button w-full md:w-auto'>Book Now</button>
              </Link>
            </div>
          </Stack__>

          {/* 9. why do clients trust cadmen clinic */}
          <section
            data-plasmic-name={"chooseBotoxSection"}
            data-plasmic-override={overrides.chooseBotoxSection}
            className={classNames(projectcss.all, sty.chooseBotoxSection)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"beforeAfterHeader"}
              data-plasmic-override={overrides.beforeAfterHeader}
              hasGap={true}
              className={classNames(projectcss.all, sty.beforeAfterHeader)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__vb63O
                )}
              >
                <React.Fragment>
                  <React.Fragment>{"Why Do Clients Trust "}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{
                      fontStyle: "italic",
                      fontWeight: 500,
                      color: "#D19D51"
                    }}
                  >
                    {"CADMEN Clinic"}
                  </span>
                  <React.Fragment>{"?"}</React.Fragment>
                </React.Fragment>
              </h2>
            </Stack__>

            <div
              style={{
                width: '95%',
                // maxWidth: '1100px',
                margin: '0 auto',
                padding: '2rem 0',
              }}
            >
              {section8cards.map(card => (
                <AlternatingInfoCard key={card.id} card={card} />
              ))}
            </div>
          </section>

          {/* 9.5 Video Section */}
          <VideoSection bgColor="bg-white" />

          {/* 10. faq, question and answer */}
          <section
            data-plasmic-name={"faqSection"}
            data-plasmic-override={overrides.faqSection}
            className={classNames(projectcss.all, sty.faqSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bvh1R)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2KoD9
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#080909" }}
                    >
                      {"Curious?"}
                    </span>
                    <React.Fragment>{" \n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic", color: "#D19D51" }}
                    >
                      {"We have answers."}
                    </span>
                  </React.Fragment>
                ) : (
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#080909" }}
                    >
                      {"Curious?"}
                    </span>
                    <React.Fragment> </React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic", color: "#D19D51" }}
                    >
                      {"We have answers."}
                    </span>
                  </React.Fragment>
                )}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___74Pg
                )}
              >
                {
                  "Contact us to schedule a FREE consultation."
                }
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__mrdPy)}
            >

              <Faq
                answer={
                  "Our commitment to personalized care, safety, and client satisfaction sets us apart. We focus on natural, long-lasting results and offer transparent pricing and rewards for loyal clients."
                }
                className={classNames("__wab_instance", sty.faq__g1EoJ)}
                question={
                  "What makes CADMEN Clinic different from other providers?"
                }
              />

              <Faq
                answer={
                  "During your consultation, our team will assess your scalp and hair concerns to craft a tailored package for you."
                }
                className={classNames("__wab_instance", sty.faq__qxO4I)}
                question={"How do I know which treatment is right for me?"}
              />

              <Faq
                answer={
                  "Yes! All clients can schedule a free follow-up appointment to check-in on their progress and address any concerns."
                }
                className={classNames("__wab_instance", sty.faq__ab5Id)}
                question={"Do you offer follow-up appointments?"}
              />

              <Faq
                answer={
                  "Within 2-4 sessions you will see improvement in your hair! Depending on the treatment, the timing varies but we recommend combining treatments (i.e., PRP + Exosomes) for optimal results."
                }
                className={classNames("__wab_instance", sty.faq__ab5Id)}
                question={"When will I see progress?"}
              />

              <Faq
                answer={
                  "Yes! New customers receive 50% off their first treatment and exclusive package pricing. "
                }
                className={classNames("__wab_instance", sty.faq__ab5Id)}
                question={"Do you have any promotions for new customers?"}
              />
              

            </Stack__>
          </section>

          {/* 11. want to learn more if our hair restoration treatments are right for you */}
          <Stack__
            as={"section"}
            data-plasmic-name={"ctaSection"}
            data-plasmic-override={overrides.ctaSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.ctaSection)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__dlFxX)}
            >
              <div
                data-plasmic-name={"heading9"}
                data-plasmic-override={overrides.heading9}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.heading9
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {"Want to learn more if our "}
                  </span>
                  <React.Fragment>{"\n"}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#E4C08C" }}
                  >
                    {"Hair Restoration Treatments are right"}
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#FFFFFF" }}
                  >
                    {" for you?"}
                  </span>
                </React.Fragment>
              </div>
              <div
                data-plasmic-name={"supportingText8"}
                data-plasmic-override={overrides.supportingText8}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.supportingText8
                )}
              >
                {"Schedule a free Consultation with our team to discuss a treatment plan tailored for you"}
              </div>
            </Stack__>

            <Link href='/book-now'  className='mt-[10px] w-full md:w-auto'>
              <button className='button white w-full md:w-auto'>Book Now</button>
            </Link>
          </Stack__>

          {/* 12. our location */}
          <OurLocationSection
            data-plasmic-name={"ourLocationSection"}
            data-plasmic-override={overrides.ourLocationSection}
            className={classNames("__wab_instance", sty.ourLocationSection)}
          />

        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "topNav",
    "topBotoxServicesSection",
    "prices",
    "heading",
    "price",
    "heading2",
    "heading3",
    "heading4",
    "heading5",
    "h1",
    "supportingText",
    "topBotoxServicesButton",
    "reviewsRatingPill",
    "benefitsOfBotoxSection",
    "benefitsOfBotoxHeader",
    "benefitsOfBotoxCards",
    "text2",
    "supportingText12",
    "text3",
    "supportingText13",
    "text4",
    "supportingText14",
    "text8",
    "supportingText18",
    "benefitsOfBotoxCardsMobile",
    "text5",
    "supportingText15",
    "text6",
    "supportingText6",
    "text7",
    "supportingText7",
    "text9",
    "supportingText16",
    "beforeAfterSection",
    "beforeAfterHeader",
    "beforeAfterSlider",
    "whatIsBotoxSection",
    "heading6",
    "supportingText5",
    "whatIsBotoxMobileText",
    "title20",
    "title21",
    "whatIsBotoxButton",
    "supportingText3",
    "supportingText4",
    "ourBotoxProcessSection",
    "ourBotoxProcessCircle",
    "ourBotoxProcessCircleBg",
    "ourBotoxProcessEllipse1",
    "ourBotoxProcessEllipse2",
    "ourBotoxProcessEllipse3",
    "ourBotoxProcessIcons",
    "ourBotoxProcessNumber",
    "ourBotoxProcessContent",
    "ourBotoxProcessButton",
    "affordableBotoxSection",
    "affordableBotoxButton",
    "faceSection",
    "areasInteractive",
    "botoxResultsSection",
    "resultCard",
    "ctaSection",
    "heading9",
    "supportingText8",
    "ctaButton",
    "isBotoxSafeSection",
    "heading10",
    "supportingText9",
    "supportingText10",
    "isBotoxRightSection",
    "isBotoxRightHeader",
    "isBotoxRightContent",
    "botoxAppointmentSection",
    "title",
    "title2",
    "title3",
    "botoxAppointmentButton",
    "botoxAppointmentMobileButton",
    "afterTheTreatmentSection",
    "afterTheTreatmentButton",
    "ageGroupsSection",
    "ageGroupsCard",
    "chooseBotoxSection",
    "chooseBotoxContent",
    "title4",
    "title5",
    "title6",
    "title7",
    "title8",
    "title9",
    "title10",
    "title11",
    "title12",
    "title13",
    "title14",
    "title15",
    "title16",
    "title17",
    "title18",
    "title19",
    "chooseBotoxImages",
    "faqSection",
    "botoxRisksSection",
    "botoxRisksNumberProgressMobile",
    "botoxRisksProgressBarMobile",
    "botoxRisksContent",
    "botoxRisksNumberProgress",
    "botoxRisksProgressBar",
    "botoxRisksImages",
    "avoidBotoxSection",
    "safetyMeasuresSection",
    "safetyMeasuresHeader",
    "safetyMeasuresContent",
    "botoxMythsSection",
    "botoxMythsSlider",
    "postTreatmentGuideSection",
    "postTreatmentGuideHeader",
    "postTreatmentGuideCards",
    "postTreatmentGuideCardsMobile",
    "postTreatmentGuideButton",
    "faq2Section",
    "ourLocationSection",
    "joinTheClubSection",
    "joinTheClubButton",
    "footerNew"
  ],

  topNav: ["topNav"],
  topBotoxServicesSection: [
    "topBotoxServicesSection",
    "prices",
    "heading",
    "price",
    "heading2",
    "heading3",
    "heading4",
    "heading5",
    "h1",
    "supportingText",
    "topBotoxServicesButton",
    "reviewsRatingPill"
  ],

  prices: ["prices", "heading", "price", "heading2", "heading3", "heading4"],
  heading: ["heading"],
  price: ["price", "heading2", "heading3"],
  heading2: ["heading2"],
  heading3: ["heading3"],
  heading4: ["heading4"],
  heading5: ["heading5", "h1"],
  h1: ["h1"],
  supportingText: ["supportingText"],
  topBotoxServicesButton: ["topBotoxServicesButton"],
  reviewsRatingPill: ["reviewsRatingPill"],
  benefitsOfBotoxSection: [
    "benefitsOfBotoxSection",
    "benefitsOfBotoxHeader",
    "benefitsOfBotoxCards",
    "text2",
    "supportingText12",
    "text3",
    "supportingText13",
    "text4",
    "supportingText14",
    "text8",
    "supportingText18",
    "benefitsOfBotoxCardsMobile",
    "text5",
    "supportingText15",
    "text6",
    "supportingText6",
    "text7",
    "supportingText7",
    "text9",
    "supportingText16"
  ],

  benefitsOfBotoxHeader: ["benefitsOfBotoxHeader"],
  benefitsOfBotoxCards: [
    "benefitsOfBotoxCards",
    "text2",
    "supportingText12",
    "text3",
    "supportingText13",
    "text4",
    "supportingText14",
    "text8",
    "supportingText18"
  ],

  text2: ["text2"],
  supportingText12: ["supportingText12"],
  text3: ["text3"],
  supportingText13: ["supportingText13"],
  text4: ["text4"],
  supportingText14: ["supportingText14"],
  text8: ["text8"],
  supportingText18: ["supportingText18"],
  benefitsOfBotoxCardsMobile: [
    "benefitsOfBotoxCardsMobile",
    "text5",
    "supportingText15",
    "text6",
    "supportingText6",
    "text7",
    "supportingText7",
    "text9",
    "supportingText16"
  ],

  text5: ["text5"],
  supportingText15: ["supportingText15"],
  text6: ["text6"],
  supportingText6: ["supportingText6"],
  text7: ["text7"],
  supportingText7: ["supportingText7"],
  text9: ["text9"],
  supportingText16: ["supportingText16"],
  beforeAfterSection: [
    "beforeAfterSection",
    "beforeAfterHeader",
    "beforeAfterSlider"
  ],

  beforeAfterHeader: ["beforeAfterHeader"],
  beforeAfterSlider: ["beforeAfterSlider"],
  whatIsBotoxSection: [
    "whatIsBotoxSection",
    "heading6",
    "supportingText5",
    "whatIsBotoxMobileText",
    "title20",
    "title21",
    "whatIsBotoxButton",
    "supportingText3",
    "supportingText4"
  ],

  heading6: ["heading6"],
  supportingText5: ["supportingText5"],
  whatIsBotoxMobileText: ["whatIsBotoxMobileText"],
  title20: ["title20"],
  title21: ["title21"],
  whatIsBotoxButton: ["whatIsBotoxButton"],
  supportingText3: ["supportingText3"],
  supportingText4: ["supportingText4"],
  ourBotoxProcessSection: [
    "ourBotoxProcessSection",
    "ourBotoxProcessCircle",
    "ourBotoxProcessCircleBg",
    "ourBotoxProcessEllipse1",
    "ourBotoxProcessEllipse2",
    "ourBotoxProcessEllipse3",
    "ourBotoxProcessIcons",
    "ourBotoxProcessNumber",
    "ourBotoxProcessContent",
    "ourBotoxProcessButton"
  ],

  ourBotoxProcessCircle: ["ourBotoxProcessCircle"],
  ourBotoxProcessCircleBg: [
    "ourBotoxProcessCircleBg",
    "ourBotoxProcessEllipse1",
    "ourBotoxProcessEllipse2",
    "ourBotoxProcessEllipse3"
  ],

  ourBotoxProcessEllipse1: ["ourBotoxProcessEllipse1"],
  ourBotoxProcessEllipse2: ["ourBotoxProcessEllipse2"],
  ourBotoxProcessEllipse3: ["ourBotoxProcessEllipse3"],
  ourBotoxProcessIcons: ["ourBotoxProcessIcons"],
  ourBotoxProcessNumber: ["ourBotoxProcessNumber"],
  ourBotoxProcessContent: ["ourBotoxProcessContent"],
  ourBotoxProcessButton: ["ourBotoxProcessButton"],
  affordableBotoxSection: ["affordableBotoxSection", "affordableBotoxButton"],
  affordableBotoxButton: ["affordableBotoxButton"],
  faceSection: ["faceSection"],
  areasInteractive: ["areasInteractive"],
  botoxResultsSection: ["botoxResultsSection", "resultCard"],
  resultCard: ["resultCard"],
  ctaSection: ["ctaSection", "heading9", "supportingText8", "ctaButton"],
  heading9: ["heading9"],
  supportingText8: ["supportingText8"],
  ctaButton: ["ctaButton"],
  isBotoxSafeSection: [
    "isBotoxSafeSection",
    "heading10",
    "supportingText9",
    "supportingText10"
  ],

  heading10: ["heading10"],
  supportingText9: ["supportingText9"],
  supportingText10: ["supportingText10"],
  isBotoxRightSection: [
    "isBotoxRightSection",
    "isBotoxRightHeader",
    "isBotoxRightContent"
  ],

  isBotoxRightHeader: ["isBotoxRightHeader"],
  isBotoxRightContent: ["isBotoxRightContent"],
  botoxAppointmentSection: [
    "botoxAppointmentSection",
    "title",
    "title2",
    "title3",
    "botoxAppointmentButton",
    "botoxAppointmentMobileButton"
  ],

  title: ["title"],
  title2: ["title2"],
  title3: ["title3"],
  botoxAppointmentButton: ["botoxAppointmentButton"],
  botoxAppointmentMobileButton: ["botoxAppointmentMobileButton"],
  afterTheTreatmentSection: [
    "afterTheTreatmentSection",
    "afterTheTreatmentButton"
  ],

  afterTheTreatmentButton: ["afterTheTreatmentButton"],
  ageGroupsSection: ["ageGroupsSection", "ageGroupsCard"],
  ageGroupsCard: ["ageGroupsCard"],
  chooseBotoxSection: [
    "chooseBotoxSection",
    "chooseBotoxContent",
    "title4",
    "title5",
    "title6",
    "title7",
    "title8",
    "title9",
    "title10",
    "title11",
    "title12",
    "title13",
    "title14",
    "title15",
    "title16",
    "title17",
    "title18",
    "title19",
    "chooseBotoxImages"
  ],

  chooseBotoxContent: [
    "chooseBotoxContent",
    "title4",
    "title5",
    "title6",
    "title7",
    "title8",
    "title9",
    "title10",
    "title11",
    "title12",
    "title13",
    "title14",
    "title15",
    "title16",
    "title17",
    "title18",
    "title19"
  ],

  title4: ["title4"],
  title5: ["title5"],
  title6: ["title6"],
  title7: ["title7"],
  title8: ["title8"],
  title9: ["title9"],
  title10: ["title10"],
  title11: ["title11"],
  title12: ["title12"],
  title13: ["title13"],
  title14: ["title14"],
  title15: ["title15"],
  title16: ["title16"],
  title17: ["title17"],
  title18: ["title18"],
  title19: ["title19"],
  chooseBotoxImages: ["chooseBotoxImages"],
  faqSection: ["faqSection"],
  botoxRisksSection: [
    "botoxRisksSection",
    "botoxRisksNumberProgressMobile",
    "botoxRisksProgressBarMobile",
    "botoxRisksContent",
    "botoxRisksNumberProgress",
    "botoxRisksProgressBar",
    "botoxRisksImages"
  ],

  botoxRisksNumberProgressMobile: ["botoxRisksNumberProgressMobile"],
  botoxRisksProgressBarMobile: ["botoxRisksProgressBarMobile"],
  botoxRisksContent: ["botoxRisksContent"],
  botoxRisksNumberProgress: ["botoxRisksNumberProgress"],
  botoxRisksProgressBar: ["botoxRisksProgressBar"],
  botoxRisksImages: ["botoxRisksImages"],
  avoidBotoxSection: ["avoidBotoxSection"],
  safetyMeasuresSection: [
    "safetyMeasuresSection",
    "safetyMeasuresHeader",
    "safetyMeasuresContent"
  ],

  safetyMeasuresHeader: ["safetyMeasuresHeader"],
  safetyMeasuresContent: ["safetyMeasuresContent"],
  botoxMythsSection: ["botoxMythsSection", "botoxMythsSlider"],
  botoxMythsSlider: ["botoxMythsSlider"],
  postTreatmentGuideSection: [
    "postTreatmentGuideSection",
    "postTreatmentGuideHeader",
    "postTreatmentGuideCards",
    "postTreatmentGuideCardsMobile",
    "postTreatmentGuideButton"
  ],

  postTreatmentGuideHeader: ["postTreatmentGuideHeader"],
  postTreatmentGuideCards: ["postTreatmentGuideCards"],
  postTreatmentGuideCardsMobile: ["postTreatmentGuideCardsMobile"],
  postTreatmentGuideButton: ["postTreatmentGuideButton"],
  faq2Section: ["faq2Section"],
  ourLocationSection: ["ourLocationSection"],
  joinTheClubSection: ["joinTheClubSection", "joinTheClubButton"],
  joinTheClubButton: ["joinTheClubButton"],
  footerNew: ["footerNew"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBotoxLander2__ArgProps,
          internalVariantPropNames: PlasmicBotoxLander2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBotoxLander2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBotoxLander2";
  } else {
    func.displayName = `PlasmicBotoxLander2.${nodeName}`;
  }
  return func;
}

export const PlasmicBotoxLander2 = Object.assign(
  // Top-level PlasmicBotoxLander2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topNav: makeNodeComponent("topNav"),
    topBotoxServicesSection: makeNodeComponent("topBotoxServicesSection"),
    prices: makeNodeComponent("prices"),
    heading: makeNodeComponent("heading"),
    price: makeNodeComponent("price"),
    heading2: makeNodeComponent("heading2"),
    heading3: makeNodeComponent("heading3"),
    heading4: makeNodeComponent("heading4"),
    heading5: makeNodeComponent("heading5"),
    h1: makeNodeComponent("h1"),
    supportingText: makeNodeComponent("supportingText"),
    topBotoxServicesButton: makeNodeComponent("topBotoxServicesButton"),
    reviewsRatingPill: makeNodeComponent("reviewsRatingPill"),
    benefitsOfBotoxSection: makeNodeComponent("benefitsOfBotoxSection"),
    benefitsOfBotoxHeader: makeNodeComponent("benefitsOfBotoxHeader"),
    benefitsOfBotoxCards: makeNodeComponent("benefitsOfBotoxCards"),
    text2: makeNodeComponent("text2"),
    supportingText12: makeNodeComponent("supportingText12"),
    text3: makeNodeComponent("text3"),
    supportingText13: makeNodeComponent("supportingText13"),
    text4: makeNodeComponent("text4"),
    supportingText14: makeNodeComponent("supportingText14"),
    text8: makeNodeComponent("text8"),
    supportingText18: makeNodeComponent("supportingText18"),
    benefitsOfBotoxCardsMobile: makeNodeComponent("benefitsOfBotoxCardsMobile"),
    text5: makeNodeComponent("text5"),
    supportingText15: makeNodeComponent("supportingText15"),
    text6: makeNodeComponent("text6"),
    supportingText6: makeNodeComponent("supportingText6"),
    text7: makeNodeComponent("text7"),
    supportingText7: makeNodeComponent("supportingText7"),
    text9: makeNodeComponent("text9"),
    supportingText16: makeNodeComponent("supportingText16"),
    beforeAfterSection: makeNodeComponent("beforeAfterSection"),
    beforeAfterHeader: makeNodeComponent("beforeAfterHeader"),
    beforeAfterSlider: makeNodeComponent("beforeAfterSlider"),
    whatIsBotoxSection: makeNodeComponent("whatIsBotoxSection"),
    heading6: makeNodeComponent("heading6"),
    supportingText5: makeNodeComponent("supportingText5"),
    whatIsBotoxMobileText: makeNodeComponent("whatIsBotoxMobileText"),
    title20: makeNodeComponent("title20"),
    title21: makeNodeComponent("title21"),
    whatIsBotoxButton: makeNodeComponent("whatIsBotoxButton"),
    supportingText3: makeNodeComponent("supportingText3"),
    supportingText4: makeNodeComponent("supportingText4"),
    ourBotoxProcessSection: makeNodeComponent("ourBotoxProcessSection"),
    ourBotoxProcessCircle: makeNodeComponent("ourBotoxProcessCircle"),
    ourBotoxProcessCircleBg: makeNodeComponent("ourBotoxProcessCircleBg"),
    ourBotoxProcessEllipse1: makeNodeComponent("ourBotoxProcessEllipse1"),
    ourBotoxProcessEllipse2: makeNodeComponent("ourBotoxProcessEllipse2"),
    ourBotoxProcessEllipse3: makeNodeComponent("ourBotoxProcessEllipse3"),
    ourBotoxProcessIcons: makeNodeComponent("ourBotoxProcessIcons"),
    ourBotoxProcessNumber: makeNodeComponent("ourBotoxProcessNumber"),
    ourBotoxProcessContent: makeNodeComponent("ourBotoxProcessContent"),
    ourBotoxProcessButton: makeNodeComponent("ourBotoxProcessButton"),
    affordableBotoxSection: makeNodeComponent("affordableBotoxSection"),
    affordableBotoxButton: makeNodeComponent("affordableBotoxButton"),
    faceSection: makeNodeComponent("faceSection"),
    areasInteractive: makeNodeComponent("areasInteractive"),
    botoxResultsSection: makeNodeComponent("botoxResultsSection"),
    resultCard: makeNodeComponent("resultCard"),
    ctaSection: makeNodeComponent("ctaSection"),
    heading9: makeNodeComponent("heading9"),
    supportingText8: makeNodeComponent("supportingText8"),
    ctaButton: makeNodeComponent("ctaButton"),
    isBotoxSafeSection: makeNodeComponent("isBotoxSafeSection"),
    heading10: makeNodeComponent("heading10"),
    supportingText9: makeNodeComponent("supportingText9"),
    supportingText10: makeNodeComponent("supportingText10"),
    isBotoxRightSection: makeNodeComponent("isBotoxRightSection"),
    isBotoxRightHeader: makeNodeComponent("isBotoxRightHeader"),
    isBotoxRightContent: makeNodeComponent("isBotoxRightContent"),
    botoxAppointmentSection: makeNodeComponent("botoxAppointmentSection"),
    title: makeNodeComponent("title"),
    title2: makeNodeComponent("title2"),
    title3: makeNodeComponent("title3"),
    botoxAppointmentButton: makeNodeComponent("botoxAppointmentButton"),
    botoxAppointmentMobileButton: makeNodeComponent(
      "botoxAppointmentMobileButton"
    ),
    afterTheTreatmentSection: makeNodeComponent("afterTheTreatmentSection"),
    afterTheTreatmentButton: makeNodeComponent("afterTheTreatmentButton"),
    ageGroupsSection: makeNodeComponent("ageGroupsSection"),
    ageGroupsCard: makeNodeComponent("ageGroupsCard"),
    chooseBotoxSection: makeNodeComponent("chooseBotoxSection"),
    chooseBotoxContent: makeNodeComponent("chooseBotoxContent"),
    title4: makeNodeComponent("title4"),
    title5: makeNodeComponent("title5"),
    title6: makeNodeComponent("title6"),
    title7: makeNodeComponent("title7"),
    title8: makeNodeComponent("title8"),
    title9: makeNodeComponent("title9"),
    title10: makeNodeComponent("title10"),
    title11: makeNodeComponent("title11"),
    title12: makeNodeComponent("title12"),
    title13: makeNodeComponent("title13"),
    title14: makeNodeComponent("title14"),
    title15: makeNodeComponent("title15"),
    title16: makeNodeComponent("title16"),
    title17: makeNodeComponent("title17"),
    title18: makeNodeComponent("title18"),
    title19: makeNodeComponent("title19"),
    chooseBotoxImages: makeNodeComponent("chooseBotoxImages"),
    faqSection: makeNodeComponent("faqSection"),
    botoxRisksSection: makeNodeComponent("botoxRisksSection"),
    botoxRisksNumberProgressMobile: makeNodeComponent(
      "botoxRisksNumberProgressMobile"
    ),
    botoxRisksProgressBarMobile: makeNodeComponent(
      "botoxRisksProgressBarMobile"
    ),
    botoxRisksContent: makeNodeComponent("botoxRisksContent"),
    botoxRisksNumberProgress: makeNodeComponent("botoxRisksNumberProgress"),
    botoxRisksProgressBar: makeNodeComponent("botoxRisksProgressBar"),
    botoxRisksImages: makeNodeComponent("botoxRisksImages"),
    avoidBotoxSection: makeNodeComponent("avoidBotoxSection"),
    safetyMeasuresSection: makeNodeComponent("safetyMeasuresSection"),
    safetyMeasuresHeader: makeNodeComponent("safetyMeasuresHeader"),
    safetyMeasuresContent: makeNodeComponent("safetyMeasuresContent"),
    botoxMythsSection: makeNodeComponent("botoxMythsSection"),
    botoxMythsSlider: makeNodeComponent("botoxMythsSlider"),
    postTreatmentGuideSection: makeNodeComponent("postTreatmentGuideSection"),
    postTreatmentGuideHeader: makeNodeComponent("postTreatmentGuideHeader"),
    postTreatmentGuideCards: makeNodeComponent("postTreatmentGuideCards"),
    postTreatmentGuideCardsMobile: makeNodeComponent(
      "postTreatmentGuideCardsMobile"
    ),
    postTreatmentGuideButton: makeNodeComponent("postTreatmentGuideButton"),
    faq2Section: makeNodeComponent("faq2Section"),
    ourLocationSection: makeNodeComponent("ourLocationSection"),
    joinTheClubSection: makeNodeComponent("joinTheClubSection"),
    joinTheClubButton: makeNodeComponent("joinTheClubButton"),
    footerNew: makeNodeComponent("footerNew"),
    // Metadata about props expected for PlasmicBotoxLander2
    internalVariantProps: PlasmicBotoxLander2__VariantProps,
    internalArgProps: PlasmicBotoxLander2__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "CadmenClinic | Hair Restoration",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBotoxLander2;
/* prettier-ignore-end */
