/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fpxTiFS69ULcX4wDGEfw3c
// Component: 4NENsursTaMC
import * as React from "react";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { useScreenVariants as useScreenVariants_4IUcgkiijTv2 } from "../blank_website/PlasmicGlobalVariant__Screen"; // plasmic-import: 4iUCGKIIJTv2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../blank_website/plasmic.module.css"; // plasmic-import: fpxTiFS69ULcX4wDGEfw3c/projectcss
import sty from "./PlasmicAreaExplainerCard.module.css"; // plasmic-import: 4NENsursTaMC/css

createPlasmicElementProxy;

export const PlasmicAreaExplainerCard__VariantProps = new Array();

export const PlasmicAreaExplainerCard__ArgProps = new Array(
  "title",
  "subtitle",
  // "button",
  "children"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAreaExplainerCard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_4IUcgkiijTv2()
  });
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__nkyaF)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/image_lab_2024/images/image19.png",
              fullWidth: 287,
              fullHeight: 256,
              aspectRatio: undefined
            }}
          />
        ),

        value: args.children
      })}
      <div className={classNames(projectcss.all, sty.freeBox__kReia)}>
        <h3
          data-plasmic-name={"h3"}
          data-plasmic-override={overrides.h3}
          className={classNames(
            projectcss.all,
            projectcss.h3,
            projectcss.__wab_text,
            sty.h3
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.title;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Forehead Lines and Frown Lines";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </h3>
        <p
          data-plasmic-name={"p"}
          data-plasmic-override={overrides.p}
          className={classNames(
            projectcss.all,
            projectcss.p,
            projectcss.__wab_text,
            sty.p
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.subtitle;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "On the forehead and between the brows for a refreshed appearance.";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </p>
        {/* <div className={classNames(projectcss.all, sty.freeBox__cg3FJ)}>
          <div className={classNames(projectcss.all, sty.freeBox__nfAxz)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $props.button;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </div>
          </div>
        </div> */}
      </div>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: ["root", "h3", "p"],
  h3: ["h3"],
  p: ["p"]
  // text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAreaExplainerCard__ArgProps,
          internalVariantPropNames: PlasmicAreaExplainerCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAreaExplainerCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAreaExplainerCard";
  } else {
    func.displayName = `PlasmicAreaExplainerCard.${nodeName}`;
  }
  return func;
}

export const PlasmicAreaExplainerCard = Object.assign(
  // Top-level PlasmicAreaExplainerCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h3: makeNodeComponent("h3"),
    p: makeNodeComponent("p"),
    // text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicAreaExplainerCard
    internalVariantProps: PlasmicAreaExplainerCard__VariantProps,
    internalArgProps: PlasmicAreaExplainerCard__ArgProps
  }
);

export default PlasmicAreaExplainerCard;
/* prettier-ignore-end */
