// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fpxTiFS69ULcX4wDGEfw3c
// Component: O0_UC5KV9F6f
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import TopNav from "../../TopNav"; // plasmic-import: xBvtLE-eO4gb/component
import BookingFlow from "../../BookingFlow"; // plasmic-import: FJd692mLTIMz/component
import FooterNew from "../../FooterNew"; // plasmic-import: NE5t6IteXed-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../blank_website/plasmic.module.css"; // plasmic-import: fpxTiFS69ULcX4wDGEfw3c/projectcss
import sty from "./PlasmicBookingsV2.module.css"; // plasmic-import: O0_UC5KV9F6f/css

createPlasmicElementProxy;

export const PlasmicBookingsV2__VariantProps = new Array();

export const PlasmicBookingsV2__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBookingsV2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <TopNav
            data-plasmic-name={"topNav"}
            data-plasmic-override={overrides.topNav}
            className={classNames("__wab_instance", sty.topNav)}
          />

          <BookingFlow
            data-plasmic-name={"bookingFlow"}
            data-plasmic-override={overrides.bookingFlow}
            className={classNames("__wab_instance", sty.bookingFlow)}
          />

          <FooterNew
            data-plasmic-name={"footerNew"}
            data-plasmic-override={overrides.footerNew}
            claimCta={null}
            className={classNames("__wab_instance", sty.footerNew)}
            color={"grey"}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "topNav", "bookingFlow", "footerNew"],
  topNav: ["topNav"],
  bookingFlow: ["bookingFlow"],
  footerNew: ["footerNew"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBookingsV2__ArgProps,
          internalVariantPropNames: PlasmicBookingsV2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBookingsV2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBookingsV2";
  } else {
    func.displayName = `PlasmicBookingsV2.${nodeName}`;
  }
  return func;
}

export const PlasmicBookingsV2 = Object.assign(
  // Top-level PlasmicBookingsV2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    topNav: makeNodeComponent("topNav"),
    bookingFlow: makeNodeComponent("bookingFlow"),
    footerNew: makeNodeComponent("footerNew"),
    // Metadata about props expected for PlasmicBookingsV2
    internalVariantProps: PlasmicBookingsV2__VariantProps,
    internalArgProps: PlasmicBookingsV2__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBookingsV2;
/* prettier-ignore-end */
